steps:
  - id: Buildpack
    name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - europe-west1-docker.pkg.dev/project-3a413078-a015-4c2b-bf4/cloud-run-source-deploy/rizalhakim33-raktracker/raktrack:$COMMIT_SHA
      - --builder=gcr.io/buildpacks/builder:latest
      - --network=cloudbuild
      - --publish
      - --path=.
      - --env
      - VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY
      - --env
      - VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN
      - --env
      - VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID
      - --env
      - VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET
      - --env
      - VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID
      - --env
      - VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - raktrack
      - --image=europe-west1-docker.pkg.dev/project-3a413078-a015-4c2b-bf4/cloud-run-source-deploy/rizalhakim33-raktracker/raktrack:$COMMIT_SHA
      - --update-labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - --region=europe-west1
      - --quiet

substitutions:
  _VITE_FIREBASE_API_KEY: AIzaSyCXMble3QQIuYbhqx45857cIYy5Q-4m_lY
  _VITE_FIREBASE_AUTH_DOMAIN: part-tracker-ed51e.firebaseapp.com
  _VITE_FIREBASE_PROJECT_ID: part-tracker-ed51e
  _VITE_FIREBASE_STORAGE_BUCKET: part-tracker-ed51e.firebasestorage.app
  _VITE_FIREBASE_MESSAGING_SENDER_ID: "965049994135"
  _VITE_FIREBASE_APP_ID: "1:965049994135:web:f6b108f62811e4d5b0d2d2"

options:
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
  substitutionOption: ALLOW_LOOSE
