steps:
  - id: Buildpack
    name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - europe-west1-docker.pkg.dev/project-3a413078-a015-4c2b-bf4/cloud-run-source-deploy/rizalhakim33-raktracker/raktrack:$COMMIT_SHA
      - --builder=gcr.io/buildpacks/builder:latest
      - --network=cloudbuild
      - --publish
      - --path=.

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - raktrack
      - --image=europe-west1-docker.pkg.dev/project-3a413078-a015-4c2b-bf4/cloud-run-source-deploy/rizalhakim33-raktracker/raktrack:$COMMIT_SHA
      - --update-labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - --region=europe-west1
      - --quiet

images:
  - europe-west1-docker.pkg.dev/project-3a413078-a015-4c2b-bf4/cloud-run-source-deploy/rizalhakim33-raktracker/raktrack:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
  substitutionOption: ALLOW_LOOSE
